# Generated by Django 4.2.23 on 2025-07-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
