# Generated by Django 4.2.23 on 2025-07-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_trip_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingTripTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trip_title', models.CharField(max_length=255)),
                ('promo_text', models.TextField(blank=True)),
                ('hero_image', models.URLField(blank=True)),
                ('itinerary', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='template',
        ),
        migrations.RemoveField(
            model_name='tripregistration',
            name='trip',
        ),
        migrations.DeleteModel(
            name='PrivateAccessToken',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='TripRegistration',
        ),
        migrations.DeleteModel(
            name='TripTemplate',
        ),
    ]
