# Generated by Django 4.2.23 on 2025-07-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_marketingtriptemplate_remove_trip_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='marketingtriptemplate',
            name='promo_text',
        ),
    ]
