# Generated by Django 4.2.23 on 2025-07-21 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_templatedestination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingtriptemplate',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='marketing.templatedestination'),
        ),
    ]
