# Generated by Django 4.2.23 on 2025-07-21 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_marketingtriptemplate_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingtriptemplate',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=128, unique=True),
        ),
    ]
