# Generated by Django 4.2.23 on 2025-07-21 16:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_quote_client_quote_departure_city_id_and_more'),
        ('marketing', '0006_marketingtriptemplate_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_title', models.CharField(max_length=255)),
                ('promo_text', models.TextField(blank=True)),
                ('hero_image', models.URLField(blank=True)),
                ('itinerary', models.JSONField(blank=True, default=list)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('departure_city', models.CharField(blank=True, max_length=255)),
                ('trip_includes', models.TextField(blank=True)),
                ('trip_not_includes', models.TextField(blank=True)),
                ('spiritual_director', models.CharField(blank=True, max_length=255)),
                ('brochure', models.URLField(blank=True)),
                ('video_link', models.URLField(blank=True)),
                ('contact_info', models.TextField(blank=True)),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='quotes.quote')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_trips', to='marketing.marketingtriptemplate')),
            ],
        ),
    ]
