# Generated by Django 4.2.23 on 2025-07-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_alter_marketingtrip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingtrip',
            name='trip_includes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketingtrip',
            name='trip_not_includes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
