# Generated by Django 4.2.23 on 2025-08-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_alter_marketingtrip_trip_includes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingtriptemplate',
            name='brochure_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='marketingtriptemplate',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='marketingtriptemplate',
            name='promo_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='marketingtriptemplate',
            name='video_link',
            field=models.URLField(blank=True),
        ),
    ]
