# Generated by Django 4.2.23 on 2025-06-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_id', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(blank=True, max_length=155)),
                ('middle_name', models.CharField(blank=True, max_length=155)),
                ('company', models.CharField(blank=True, max_length=155, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=35, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=45)),
                ('phone2', models.CharField(blank=True, max_length=45)),
                ('phone3', models.CharField(blank=True, max_length=45)),
                ('mobile', models.CharField(blank=True, max_length=45)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('email2', models.CharField(blank=True, max_length=255)),
                ('email3', models.CharField(blank=True, max_length=255)),
                ('email_maillist', models.CharField(blank=True, max_length=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=7)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('ems_name', models.CharField(blank=True, max_length=150)),
                ('ems_phone', models.CharField(blank=True, max_length=50)),
                ('pp_number', models.CharField(blank=True, max_length=50)),
                ('pp_date_issue', models.DateField(blank=True, null=True)),
                ('pp_date_expire', models.DateField(blank=True, null=True)),
                ('pp_place_issue', models.CharField(blank=True, max_length=150)),
                ('pp_nationality', models.CharField(blank=True, max_length=200)),
                ('pp_visa', models.CharField(default='N', max_length=1)),
                ('pp_visa_note', models.CharField(blank=True, max_length=255)),
                ('pp_visa_received', models.CharField(default='N', max_length=1)),
                ('want_single_room', models.CharField(blank=True, max_length=1)),
                ('want_roomate', models.CharField(blank=True, max_length=1)),
                ('have_roomate_flag', models.CharField(blank=True, db_column='have_roomate', max_length=1)),
                ('have_roomate_name', models.CharField(blank=True, max_length=150)),
                ('registered_at_event', models.CharField(blank=True, max_length=1)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('mail_lists', models.CharField(blank=True, max_length=255)),
                ('name_tag', models.CharField(blank=True, max_length=255)),
                ('from_web', models.CharField(default='N', max_length=1)),
                ('hearabout', models.CharField(blank=True, max_length=255)),
                ('unique_ident', models.CharField(blank=True, max_length=35)),
            ],
            options={
                'db_table': 'client',
                'ordering': ['last_name', 'first_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=155, unique=True)),
            ],
            options={
                'verbose_name': 'Client Type',
                'verbose_name_plural': 'Client Types',
                'db_table': 'client_type',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
    ]
