# Generated by Django 4.2.23 on 2025-06-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_spa', models.CharField(blank=True, max_length=255, null=True)),
                ('template', models.TextField(blank=True, null=True)),
                ('template_spa', models.TextField(blank=True, null=True)),
                ('it_template', models.TextField(blank=True, null=True)),
                ('it_template_spa', models.TextField(blank=True, null=True)),
                ('trip_days', models.IntegerField()),
                ('prep_guide1', models.IntegerField(blank=True, null=True)),
                ('prep_guide2', models.IntegerField(blank=True, null=True)),
                ('prep_guide3', models.IntegerField(blank=True, null=True)),
                ('prep_guide4', models.IntegerField(blank=True, null=True)),
                ('reminder_sheet1', models.IntegerField(blank=True, null=True)),
                ('reminder_sheet2', models.IntegerField(blank=True, null=True)),
                ('reminder_sheet3', models.IntegerField(blank=True, null=True)),
                ('reminder_sheet4', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'db_table': 'destination',
            },
        ),
        migrations.CreateModel(
            name='DestinationGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Destination Group',
                'verbose_name_plural': 'Destination Groups',
                'db_table': 'destination_group',
            },
        ),
    ]
