# Generated by Django 4.2.23 on 2025-06-29 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_destination_destinationgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'managed': False, 'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.AlterModelOptions(
            name='destinationgroup',
            options={'managed': False, 'verbose_name': 'Destination Group', 'verbose_name_plural': 'Destination Groups'},
        ),
    ]
