# Generated by Django 4.2.23 on 2025-07-21 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0004_alter_quote_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='marketing_private_link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='marketing_public_link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
