# Generated by Django 4.2.23 on 2025-07-21 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0005_quote_client_quote_departure_city_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(db_column='client_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.client'),
        ),
        migrations.AddField(
            model_name='quote',
            name='departure_city_id',
            field=models.ForeignKey(db_column='departure_city_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.itinerarycity'),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_status',
            field=models.ForeignKey(db_column='quote_status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.quotestatus'),
        ),
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='workflow_status_rel',
            field=models.ForeignKey(blank=True, db_column='workflow_status', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.quoteworkflow'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
