# Generated by Django 4.2.23 on 2025-06-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=45, unique=True)),
                ('clave', models.CharField(blank=True, max_length=50, null=True)),
                ('grupo_id', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='YES', max_length=3)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('u_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('u_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('idioma', models.CharField(default='ENGLISH', max_length=15)),
                ('acceso_ultimo', models.DateTimeField(blank=True, null=True)),
                ('acceso_intentos', models.IntegerField(default=0)),
                ('telefono_fijo', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_movil', models.CharField(blank=True, max_length=50, null=True)),
                ('comision', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('agent', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
